### ISSUE TITLE
Building fails for Win64

### ISSUE THREAD

**Issue by jrappen** [lumios/eew#19]
```text
λ gulp build:win64
[21:11:54] Working directory changed to ~\Downloads\shake
[21:11:54] Using gulpfile ~\Downloads\shake\gulpfile.js
[21:11:54] Starting 'build:win64'...
[21:11:54] Finished 'build:win64' after 9.73 ms
[21:11:54] gulp-electron download skip: already exists
[21:11:54] > 7z x ~\Downloads\shake\build\cache\v0.37.6\electron-v0.37.6-win32-x64.zip -o~\Downloads\shake\build\cache\v0.37.6\electron-v0.37.6-win32-x64
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn 7z ENOENT
    at exports._errnoException (util.js:1033:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by KyeNormanGill** [comment]
This api only works on macOS
> https://github.com/lumios/shake/issues/17

**Comment by kurisubrooks** [comment]
@KyeNormanGill Only the auto update works on macOS and has not been implemented.

@jrappen Unfortunately this project is sort of deprecated, as i've moved on to incorporating Shake core functionality in other projects. If you're interested, I can walk you through my new Internal API for Shake if you'd like to make your own client for Shake (personal-use only), but otherwise I do not plan on updating this project.
