### ISSUE TITLE
Unknown XML Related Errors

### ISSUE THREAD

**Issue by kurisubrooks** [lumios/eew#4]
Using the official API, unknown as to why this is happening.

```
Error: There are errors in your xml file: mismatched tag
    at Object.module.exports [as toJson] (/home/kurisu/eew/node_modules/xml2json/lib/xml2json.js:153:15)
    at Request.read [as _callback] (/home/kurisu/eew/index.js:52:35)
    at Request.self.callback (/home/kurisu/eew/node_modules/request/request.js:197:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/kurisu/eew/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/kurisu/eew/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

**Comment by Penagwin** [comment]
Assuming this was fixed?

**Comment by kurisubrooks** [comment]
It was eradicated as we moved the parsing to the server.
