### ISSUE TITLE
Unable to fetch Babylon

### ISSUE THREAD

**Issue by kurisubrooks** [lumios/eew#6]
```
Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\kuris>cd code
C:\Users\kuris\Code>cd eew
C:\Users\kuris\Code\eew>npm install
npm WARN deprecated node-webkit-builder@1.0.13: WARNING: This module has been renamed to nw-builder. Install using nw-builder instead, node-webkit-builder willno longer be updated.
npm WARN peerDependencies The peer dependency browserify@>= 2.3.0 < 4 included from browserify-shim will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on itexplicitly.
/

> electron-prebuilt@0.29.2 postinstall C:\Users\kuris\Code\eew\node_modules\electron-prebuilt
> node install.js

npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: babylon@'>=5.8.4 <6.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","5.6.23","5.7.1","5.7.2","5.8.2","5.8.3"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'babel-core'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     
C:\Users\kuris\Code\eew\npm-debug.log
```

**Comment by Penagwin** [comment]
This is a weird issue... If we skip ES6 support we will drop half the dependencies. Ill pull it in a in a few hours.

**Comment by kurisubrooks** [comment]
Now it throws:

``` node
Kurisus-MBP:src Kurisu$ node index.js
/Users/Kurisu/Code/eew/node_modules/zepto-browserify/zepto.js:5
    document = window.document,
               ^
ReferenceError: window is not defined
    at /Users/Kurisu/Code/eew/node_modules/zepto-browserify/zepto.js:5:16
    at Object.<anonymous> (/Users/Kurisu/Code/eew/node_modules/zepto-browserify/zepto.js:882:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Kurisu/Code/eew/src/index.js:8:9)
    at Module._compile (module.js:460:26)
```

**Comment by Penagwin** [comment]
Oh, you are trying to make a CLI version. 

You aren't launching it with electron which means it isnt in Chromium. Window, zepto, etc only work if there is a DOM (If it is part of a webpage).

I can attempt to separate the the CLI and GUI, so they are each in in their separate files, but don't copy code(GUI will require the CLI).

**Comment by kurisubrooks** [comment]
Yup, that way we'd be able to run it on Linux, without the need of a GUI. :smile:

**Comment by kurisubrooks** [comment]
Fixed with rewrite
